default["quantum"]["custom_template_banner"] = "
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
"

default["quantum"]["keystone_service_chef_role"] = "keystone"
default["quantum"]["quantum_service_chef_role"] = "quantum"
default["quantum"]["rabbit_server_chef_role"] = "rabbitmq-server"

default["quantum"]["interface_plugin"] = "openvswitch"
default["quantum"]["openvswitch"]["ini_file"] =
  "/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini"
default["quantum"]["l3-agent"]["ini_file"] = "/etc/quantum/l3_agent.ini"
default["quantum"]["dhcp-agent"]["ini_file"] = "/etc/quantum/dhcp_agent.ini"
default["quantum"]["metadata-agent"]["ini_file"] = "/etc/quantum/metadata_agent.ini"


default["quantum"]["db"]["username"] = "quantum"

default["quantum"]["service_tenant_name"] = "service"
default["quantum"]["service_user"] = "quantum"
default["quantum"]["service_role"] = "admin"
default["quantum"]["service_role"] = "admin"
default["quantum"]["region"] = "RegionOne"
default["quantum"]["server"]["auth"]["cache_dir"] = "/var/cache/quantum/server"


default["quantum"]["verbose"] = "True"
default["quantum"]["debug"] = "True"
default["quantum"]["state_path"] = "/var/lib/quantum"
default["quantum"]["log_dir"] = "/var/log/quantum"
default["quantum"]["bind_interface"] = "lo"
default["quantum"]["bind_port"] = "9696"
default["quantum"]["core_plugin_list"] = {
  "LinuxBridgePluginV2" => "quantum.plugins.linuxbridge.lb_quantum_plugin.LinuxBridgePluginV2",
  "OVSQuantumPluginV2" => "quantum.plugins.openvswitch.ovs_quantum_plugin.OVSQuantumPluginV2"
}
default["quantum"]["core_plugin"] = default["quantum"]["core_plugin_list"]["OVSQuantumPluginV2"]
# array of service plugins
default["quantum"]["service_plugins"] = []
default["quantum"]["auth_strategy"] = "keystone"
default["quantum"]["base_mac"] = "fa:16:3e:00:00:00"
default["quantum"]["mac_generation_retries"] = "16"
default["quantum"]["dhcp_lease_duration"] = "120"
default["quantum"]["dhcp_agent_notification"] = "True"
default["quantum"]["allow_bulk"] = "True"
default["quantum"]["allow_pagination"] = "False"
default["quantum"]["allow_sorting"] = "False"
default["quantum"]["allow_overlapping_ips"] = "False"
default["quantum"]["force_gateway_on_subnet"] = "False"
default["quantum"]["rpc_backend"] = "quantum.openstack.common.rpc.impl_kombu"
default["quantum"]["rpc_thread_pool_size"] = "64"
default["quantum"]["rpc_conn_pool_size"] = "30"
default["quantum"]["rpc_response_timeout"] = "60"
default["quantum"]["rpc_cast_timeout"] = "30"
default["quantum"]["allowed_rpc_exception_modules"] = "quantum.openstack.common.exception, nova.exception"
default["quantum"]["control_exchange"] = "quantum"
default["quantum"]["fake_rabbit"] = "False"
default["quantum"]["rabbit_host"] = "localhost"
default["quantum"]["rabbit_password"] = "guest"
default["quantum"]["rabbit_port"] = "5672"
default["quantum"]["rabbit_userid"] = "guest"
default["quantum"]["rabbit_virtual_host"] = "/"
default["quantum"]["rabbit_max_retries"] = "0"
default["quantum"]["rabbit_retry_interval"] = "0"
# Possible values:
# quantum.openstack.common.notifier.no_op_notifier
# quantum.openstack.common.notifier.log_notifier
# quantum.openstack.common.notifier.rpc_notifier
default["quantum"]["notification_driver_list"] = {
  "no_op_notifier" => "quantum.openstack.common.notifier.no_op_notifier",
  "log_notifier" => "quantum.openstack.common.notifier.log_notifier",
  "rpc_notifier" => "quantum.openstack.common.notifier.rpc_notifier"
}
default["quantum"]["notification_driver"] = default["quantum"]["notification_driver_list"]["log_notifier"]
default["quantum"]["default_notification_level"] = "INFO"
default["quantum"]["default_publisher_id"] = 'myhost.com'
default["quantum"]["notification_topics"] = "notifications"
default["quantum"]["pagination_max_limit"] = "-1"
default["quantum"]["max_dns_nameservers"] = "5"
default["quantum"]["max_subnet_host_routes"] = "20"
default["quantum"]["max_fixed_ips_per_port"] = "5"
default["quantum"]["agent_down_time"] = "5"
default["quantum"]["network_scheduler_driver_list"] = {
  "ChanceScheduler" => "quantum.scheduler.dhcp_agent_scheduler.ChanceScheduler"
}
default["quantum"]["network_scheduler_driver"] = default["quantum"]["network_scheduler_driver_list"]["ChanceScheduler"]
default["quantum"]["router_scheduler_driver_list"] = {
  "ChanceScheduler" => "quantum.scheduler.l3_agent_scheduler.ChanceScheduler"
}
default["quantum"]["router_scheduler_driver"] = default["quantum"]["router_scheduler_driver_list"]["ChanceScheduler"]
default["quantum"]["network_auto_schedule"] = "True"
default["quantum"]["router_auto_schedule"] = "True"
default["quantum"]["quotas"]["quota_items"] = {
  "network" => "10",
  "subnet" => "10",
  "port" => "10"
}
default["quantum"]["quotas"]["default_quota"] = "-1"
default["quantum"]["quotas"]["driver"] = "quantum.quota.ConfDriver"
default["quantum"]["agent"]["root_helper"] = "sudo quantum-rootwrap /etc/quantum/rootwrap.conf"
default["quantum"]["agent"]["report_interval"] = "4"
default["quantum"]["database"]["sql_max_retries"] = "10"
default["quantum"]["database"]["reconnect_interval"] = "2"
default["quantum"]["database"]["sql_dbpool_enable"] = "False"
default["quantum"]["database"]["sql_min_pool_size"] = "1"
default["quantum"]["database"]["sql_max_pool_size"] = "5"
default["quantum"]["database"]["sql_idle_timeout"] = "3600"
default["quantum"]["ovs"]["tenant_network_type_list"] = {
  "local" => "local",
  "gre" => "gre",
  "vlan" => "vlan"
}
default["quantum"]["ovs"]["tenant_network_type"] = default["quantum"]["ovs"]["tenant_network_type_list"]["gre"]
default["quantum"]["ovs"]["network_vlan"]["physnet"] = "physnet1"
default["quantum"]["ovs"]["network_vlan"]["bridge"] = "br-fixed"
default["quantum"]["ovs"]["network_vlan"]["min"] = "1000"
default["quantum"]["ovs"]["network_vlan"]["max"] = "2999"
default["quantum"]["ovs"]["enable_tunneling"] = "True"
default["quantum"]["ovs"]["tunnel_id"]["min"] = "1"
default["quantum"]["ovs"]["tunnel_id"]["max"] = "1000"
default["quantum"]["ovs"]["integration_bridge"] = "br-int"
default["quantum"]["ovs"]["tunnel_bridge"] = "br-tun"
default["quantum"]["ovs"]["int_peer_patch_port"] = "patch-tun"
default["quantum"]["ovs"]["tun_peer_patch_port"] = "patch-int"
default["quantum"]["ovs"]["local_interface"] = "eth0"
default["quantum"]["use_namespaces"] = "True"
default["quantum"]["external_bridge"] = "br-ex"
default["quantum"]["interface_driver_list"] = {
	"OVSInterfaceDriver" => "quantum.agent.linux.interface.OVSInterfaceDriver",
	"BridgeInterfaceDriver" => "quantum.agent.linux.interface.BridgeInterfaceDriver"
}
default["quantum"]["l3-agent"]["interface_driver"] = default["quantum"]["interface_driver_list"]["OVSInterfaceDriver"]
default["quantum"]["l3-agent"]["use_namespacse"] = default["quantum"]["use_namespaces"]
default["quantum"]["l3-agent"]["metadata_port"] = "9697"
default["quantum"]["l3-agent"]["send_arp_for_ha"] = "3"
default["quantum"]["l3-agent"]["periodic_interval"] = "40"
default["quantum"]["l3-agent"]["periodic_fuzzy_delay"] = "5"
default["quantum"]["dhcp-agent"]["resync_interval"] = "5"
default["quantum"]["dhcp-agent"]["interface_driver"] = default["quantum"]["interface_driver_list"]["OVSInterfaceDriver"]
default["quantum"]["dhcp-agent"]["dhcp_driver"] = "quantum.agent.linux.dhcp.Dnsmasq"
default["quantum"]["dhcp-agent"]["use_namespaces"] = default["quantum"]["use_namespaces"]
	
case node["platform"]
when "suse"
  default["quantum"]["user"] = "openstack-quantum"
  default["quantum"]["group"] = "openstack-quantum"
  default["quantum"]["platform"] = {
    "mysql_python_packages" => [ "python-mysql" ],
    "keystone_python_packages" => [ "python-keystone" ],
    "quantum_common_packages" => [ "openstack-quantum", "python-quantumclient" ],
    "quantum_server_packages" => [ "openstack-quantum-server"],
    "quantum_l3_agent_packages" => [ "openstack-quantum-l3-agent"],
    "quantum_metadata_agent_packages" => [ "openstack-quantum-metadata-agent"],
    "quantum_dhcp_agent_packages" => [ "openstack-quantum-dhcp-agent"],
    "quantum_openvswitch_agent_packages" => [ "openstack-quantum-openvswitch-agent"],
    "quantum_server_service" => "openstack-quantum",
    "quantum_l3_agent_service" => "openstack-quantum-l3-agent",
    "quantum_metadata_agent_service" => "openstack-quantum-metadata-agent",
    "quantum_dhcp_agent_service" => "openstack-quantum-dhcp-agent",
    "quantum_openvswitch_agent_service" => "openstack-quantum-openvswitch-agent",
    "quantum_linuxbridge_agent_service" => "openstack-quantum-linuxbridge-agent",
    "quantum_server_process_name" => "quantum-server",
    "quantum_l3_agent_process_name" => "quantum-l3-agent",
    "quantum_metadata_agent_process_name" => "quantum-metadata-agent",
    "quantum_dhcp_agent_process_name" => "quantum-dhcp-agent",
    "quantum_openvswitch_agent_process_name" => "quantum-openvswitch-agent",
    "quantum_linuxbridge_agent_process_name" => "quantum-linuxbridge-agent",
    "package_overrides" => ""
  }

end
